### ISSUE TITLE
add further context menu option

### ISSUE THREAD

**Issue by tokariu** [Yukisama/TextLinkyTool#14]
hello,

I'm glad there is this webextension addon. I was a big fan of the XUL based "Linky" addon and I was looking for a WE addon that fills the gap. TextLinkyTool is pretty close to that.

However I miss some of the options I got there:
![linky](https://user-images.githubusercontent.com/7195846/44868678-c7f5b380-ac8b-11e8-9657-96f62d29c993.png)

Would it be possible to add these in the WE version?

**Comment by Yukisama** [comment]
Hi,

The addon "Linky" has 11 features:

1. Sum links count and image links count 
=>The "sum links count" feature will not be implemented in "Text Linky Tool".
Because it dynamically parses all page text to get links, and most pages are not static.
Every time use a lot of memory resources on the content menu display, it not good.

2. Open Selected Links in tabs 
=> "Text Linky Tool" is mixed Links and text links.
I will add "link object only" on later version.

3. Open Selected Text Link in tabs 
=> Already have

4. Open All Links in tabs
=> Already have

5. Open All Image Links in tabs
=> The feature will not be implemented in "Text Linky Tool".
Because it not very useful.
Open link list to tabs should be try the other extensions like "Open Multiple Addresses" ( https://addons.mozilla.org/firefox/addon/open-multiple-addresses )

6. Show All Image Links in one tab 
=> The feature will not be implemented in "Text Linky Tool".
Please use "copy all image links" feature and paste on text editor. (e.g. windows notepad)

7. Show All Images in one tab
=> Already have

8. Copy All Links to Clipboard
=> Already have

9. Copy Selected Links to Clipboard
=> Already have.

10. Download All Links
=> The download relation features will not be implemented in "Text Linky Tool".
Please use "copy all links" feature and paste on download software.

11. Download Selected Links
=> The download relation features will not be implemented in "Text Linky Tool".
Please use "copy selected links" feature and paste on download software.

Thanks your information. 
Very helpful to me.

**Comment by tokariu** [comment]
Thanks for the detailed response!

I want to get a bit more into some of the points:

1. I understand the problem with memory resources if it is handled that way. But maybe there is another approach for the sum of all links+images.
How about counting the links/images just once on every page load? just ignoring non-static pages. I guess the old Linky does the same. Whenever I had a look at the counter in old Linky it was just to get a glimpse of the amount of images and links on the initial page load. So I knew exactly what to expect when I use "open all links" and the counter said 300+...
anyway, the counter was for sure not the most important thing of the addon.

2. Open Selected Links in tabs: the key here was that the user is able to mark some of the link-texts (not necessarily the complete text of the link) and Linky correctly copied all the href URLs of the marked links.

3.  Open Selected Text Link in tabs: luckily there is an option in the settings to raise the limit of 5 tabs at once. because I often used to open something like 50-100 links at once and it's been working without problem for years. maybe this default limit is a bit low nowadays. 

4. Open All Links in tabs: the same as above, if the limit was not adjusted in the settings, 5 urls limit warning is a bit harsh.
And maybe it's a smarter to rename "Open Page URLs" to something like "Open All links in Tabs", which is more clear what it does: Some people don't know what an URL is, but they know what a link is. "Page" is not necessary to mention imho because it's pretty clear that the current page is meant if the user opens the context menu from there. "Tabs" might be worth to mention, otherwise the user doesn't know if it opens a lot of windows or just tabs. (all this is just fine tuning, not really necessary to mention, but anyway...)

5. Open All Image Links in tabs: This is actually one of the most important features that old linky got and it's indeed very useful. I know that there are addons where you can paste a list of links and it opens the links in tabs. but this is cumbersome! imagine, there are so many image galleries, where something like 9-12 thumbnails on one page are linked to the original sized images. with this linky feature you would just say: open all image links in tabs/one tab and you get all the full sized images without copypasta lists of links to other addons/downloaders. This is comfort. this is what people want :)

6. Show All Image Links in one tab: the same as mentioned in 5.

7. Show All Images in one tab: great that it's available.
but this feature is mainly usefull if the original sized images are already shown on the page. most often these are just thumbnails. of course there are some other use cases.
    
8. Copy All Links to Clipboard: I guess it's called "Copy Page URLs (Custom)" but again i think it would be more clear to users when it's actually called something like "Copy All Links to Clipboard".

9. Copy Selected Links to Clipboard: the same as 8. 

10. Download All Links. I really miss that feature. and it's really cumbersome to use 3rd party software to fill the gap.. you need some extra steps everytime. it's would be so much more comfortable if it's already in the browser. However, i don't know if it's possible with webextentions to hand over the links to the internal download-manager. but if it's possible.. please don't completely ignore this feature!

11. Download Selected Links: same as 10.

so far, I hope I could elaborate some of the old linky features.

**Comment by Yukisama** [comment]
Browser extension should be "Single responsibility principle"
So I will not to add TextEditor and DownloadManager feature.
Please use 3rd software to edit text and download files.
