### ISSUE TITLE
[Request] Add "Copy as Markdown" option

### ISSUE THREAD

**Issue by sbstn87** [Yukisama/TextLinkyTool#17]
Hi,

could you ad a new option to copy selection as markdown?

Perhaps you could reuse the source code of this extension:
https://github.com/0x6b/copy-selection-as-markdown

Currently I use your extension and the second one, it would be great if there was just one with a merged functionality.

Regards,
Sebastian

**Comment by Yukisama** [comment]
Hi,

Text Linky Tool allows add new custom formats.
Markdown format like this `[[name]]([[url]])`, it can be added on options page.
And also can be removed no used foramts on options page.

**Comment by Yukisama** [comment]
No response over 7 day.
Issue close.

**Comment by smaragdus** [comment]
The Markdown format that works for me is this:

`[[[name]]]([[url]])`

I suggest that in new versions of [Text Linky Tool](https://github.com/Yukisama/TextLinkyTool) you add it as default format for:

- Copy Link info - Format:
- Copy Tab info - Format:

since Markdown is a very common format. If Markdown is added to default formats the user would not need to add it manually.

**Comment by Yukisama** [comment]
Everyone has different habits, I would like no default formats.
Maybe provide samples in TextLinkyTool is better.
Thanks for your suggestion.

**Comment by smaragdus** [comment]
@Yukisama 

> Maybe provide samples in TextLinkyTool is better.

Ready-made samples would be fine.

Also, you may add a document (perhaps to  project wiki page) with samples of common formats.
